production: true
# Site settings
title: PhoneGap
description: "Easily create apps using the web technologies you know and love: HTML, CSS, and JavaScript."
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://phonegap.com" # the base hostname & protocol for your site
twitter_username: phonegap
github_username:  phonegap

paginate: 10
paginate_path: "/blog/page:num/"

# Build settings
markdown: kramdown

permalink: /:categories/:year/:month/:day/:title/
highlighter: pygments
excerpt_separator: <!--more-->
exclude: [vendor]
sass:
  sass_dir: _sass
  style: compressed
